### ISSUE TITLE
issues here and there

### ISSUE THREAD

**Issue by ArghKevin** [boxcrittersmods/bc-texture-pack-manager#9]
**Describe the bug**
quite frequently, the textures will not change when selected or deselected, sometimes due to reload times, other times at random
in addition, while i doubt this has anything to do with the manager itself, most textures are no longer working
**To Reproduce**
when it happens it happens at random(my bad if that isnt very helpful)

**Envirement Info (please complete the following information):**
 - Device: [Mobile/Desktop] Acer Chromebook
 - OS: [e.g. iOS] CHromeOS
 - Browser [e.g. chrome, safari]CHrome
 - TexturePack Manager Version:  [e.g. 22] while these problems were much more apparent in earlier versions, these things still occasionally happen now
 - Texture Pack: [url or tp code]

**Console Output**
nothing irregular

**Comment by torralbaa** [comment]
Hello @ArghKevin! The information that you provide is very vague, then we can't reproduce the issue.

Is the bug still present in 3.x.x versions?

**Comment by torralbaa** [comment]
Ok, I will close this issue due to inactivity and because the bugs aren't be reproducible.
